name: Terraform Apply
description: "Terraform Apply action"

inputs:
  path:
    description: "Path of Terraform code"
    required: true
  label:
    description: "A name for the plan"
    required: false
  backend_config_file:
    description: "Backend config file"
    required: false
  var_file:
    description: "List of tfvars files"
    required: false
  auto_approve:
    description: "Approve without pull request"
    required: false
  args:
    description: "Additional terraform arguments"
    required: false

runs:
  using: "composite"
  steps:
    - name: Terraform Apply
      uses: dflook/terraform-apply@v1
      with:
        path: ${{ inputs.path }}
        label: ${{ inputs.label }}
        backend_config_file: ${{ inputs.backend_config_file }}
        var_file: ${{ inputs.var_file }}
        auto_approve: ${{ inputs.auto_approve }}
        args: ${{ inputs.args }}


